### ISSUE TITLE
Mining levels on the harvestability overlay don't display correctly with latest IguanaTweaks.

### ISSUE THREAD

**Issue by SargeRyong** [squeek502/WailaHarvestability#20]
Using WailaHarvestability 1.0.4, TCon 1.6.0d40.1, and IguanaTweaks 2.0.2.

After upgrading to latest TCon and IguanaTweaks, all mining levels on the overlay display as "<Unknown>", rather than the correct mining level.  The text is still color-coded correctly and whether or not the block is currently harvestable is still correct.

**Comment by squeek502** [comment]
Ah, yeah, will fix this. Thanks.

**Comment by ghost** [comment]
Built and tested OK.

In: ProxyIguanaTweaks.java

Change: IguanaTweaksTConstruct = Class.forName("iguanaman.iguanatweakstconstruct.IguanaTweaksTConstruct");

To: IguanaTweaksTConstruct = Class.forName("iguanaman.iguanatweakstconstruct.util.HarvestLevels");
