### ISSUE TITLE
GregTech ores not showing correct harvest level

### ISSUE THREAD

**Issue by squeek502** [squeek502/WailaHarvestability#28]
From IRC:

> `<SoundLogic> WAILIA harvestability lists them as harvistable and doesn't list a harvest level`

**Comment by LemADEC** [comment]
Issue seems to be still live. Any idea what's causing it?

**Comment by squeek502** [comment]
I would assume GregTech uses it's own harvest level code rather than the Forge methods. Will need to look into it more.

**Comment by Blood-Asp** [comment]
GT ores are TileEntitys to save 32000 different ores in one block id. The Harvestlevel is saved as Block meta:  https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/common/blocks/GT_Block_Ores.java#L135
The block meta is set on placement: https://github.com/Blood-Asp/GT5-Unofficial/blob/master/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L33

**Comment by squeek502** [comment]
Much appreciated @Blood-Asp. Will add support when I get the chance.

**Comment by squeek502** [comment]
Turned out to be simpler than I thought; GregTech implements all the Forge methods properly, there was just some code for handling disguised blocks that was getting in the way (where the ItemStack provided by Waila differs from the block in the world), causing the actual block's metadata to be discarded. Committing a fix now.

**Comment by LemADEC** [comment]
Thanks!
