### ISSUE TITLE
Extra server->client dependency

### ISSUE THREAD

**Issue by Player3324** [squeek502/WailaHarvestability#30]
Waila itself doesn't need to be installed if the server has it, but this mod requires it. Fixing it would require something along the lines of setting acceptableRemoteVersions = "*" in @Mod and potentially also making sure it's still compatible/detecting if versions are mismatched then.

Being able to remove Waila is quite important for some users to simply not see it, save bandwidth or work around issues.

**Comment by squeek502** [comment]
Will do. Thanks for reporting it.

**Comment by squeek502** [comment]
Will be in the next version. Note also that this mod has no server-side functionality; the mod could simply be removed from the server to fix this in the meantime.
