### ISSUE TITLE
Any point to installing serverside?

### ISSUE THREAD

**Issue by Razorskills** [squeek502/WailaHarvestability#31]
Hello, I was wondering if like waila there is any usefulness to installing it on the serverside?

I have noticed that if I install it on the server, it will then require the clients to also have the mod and not allow them in. Any reason behind that?

**Comment by squeek502** [comment]
Nope, no point in having it server-side. See https://github.com/squeek502/WailaHarvestability/issues/30

**Comment by Razorskills** [comment]
ah ok thanks, I probably should have had a look in old issues before hand
