### ISSUE TITLE
ToolHelper.isToolEffectiveAgainst uses vanilla break speed method instead of Forge method

### ISSUE THREAD

**Issue by Choonster** [squeek502/WailaHarvestability#38]
The [last line](https://github.com/squeek502/WailaHarvestability/blob/97cb98247ffc8cce6292d2cc3baf2496bfb6cc32/java/squeek/wailaharvestability/helpers/ToolHelper.java#L113) of `ToolHelper.isToolEffectiveAgainst` uses the vanilla `ItemStack#func_150997_a` method to get the tool's break speed for the block, but it should probably use the Forge-provided `Item#getDigSpeed` method instead since this is used for the actual break speed calculations when breaking blocks.

**Comment by squeek502** [comment]
Good call, thanks for letting me know about that.

**Comment by Choonster** [comment]
Thanks for the quick fix. This should allow my custom swords to show as effective tools for Cobwebs.

**Comment by squeek502** [comment]
Released here: https://github.com/squeek502/WailaHarvestability/releases/tag/v1.1.5
