### ISSUE TITLE
PC Crash when using wailaharvestability

### ISSUE THREAD

**Issue by Frobuzmumber** [squeek502/WailaHarvestability#50]
I have been having an issue with my computer crashing while playing modded Minecraft since they updated Windows 10 (about a month and a halfish) to the newer version. I have traced the issue to this mod. When I have this mod installed, it crashes (randomly) and when this mod is removed I can play for hours without any issues. I have tried 1.7.10 versions and 1.10.2 versions and even 1.8.9 versions and they seem to do the same thing. It makes no difference what other mods exist in the pack. I have no logs as the computer literally freezes and I have to force reboot in order to recover. There was no issues before windows updated. I really enjoy this mod and I hope a resolution can be found so that I can use it once again. If you need any further information, feel free to message me.

**Comment by squeek502** [comment]
Unfortunately, I have no idea how to possibly debug this. Waila Harvestability is doing nothing special at all--basically everything is using either standard Waila, standard Forge, or standard Minecraft methods--so I don't even know where to start looking for the cause of a system crash.
