### ISSUE TITLE
1.12 Minecraft World not Loading

### ISSUE THREAD

**Issue by Imnuts7** [squeek502/WailaHarvestability#56]
With the mod installed loading/creating a world gets stuck on 'Loading World'.
fml-client-latest: https://gist.github.com/Imnuts7/ebc9dd5990982e428f24d42d3bf9b764
fml-junk-earlystartup (contains crucial information): https://gist.github.com/Imnuts7/8ecb86a4e79a7f55bfc16d68db18861c

**Comment by squeek502** [comment]
Thanks for reporting this, will get it fixed soon.

**Comment by squeek502** [comment]
Should be fixed in 1.1.11: https://minecraft.curseforge.com/projects/waila-harvestability/files/2452291
