### ISSUE TITLE
[1.16.1] Currently harvastable tooltip is wrong says block is always harvestable when for example using a wooden pickaxe.

### ISSUE THREAD

**Issue by Gbergz** [squeek502/WailaHarvestability#72]
Title^

This is not the case on the 1.15.2 version though, there it works like normal.

### Versions
**Minecraft:** 1.16.1
**HWYLA:** 1.10.10-B77_1.16.1
**Waila Harvestability:** mc1.16.1-forge-1.1.12
**Forge:** 32.0.106

### Examples

**1.15.2 Working as intended:**
![image](https://user-images.githubusercontent.com/26634554/89712861-e4c8b480-d993-11ea-9707-05497b593ba8.png)

**1.16.1 Not Working as intended:**
![image](https://user-images.githubusercontent.com/26634554/89713244-b5677700-d996-11ea-90de-a9182af7dbbd.png)

Thought it would be a good idea to report this!

Thanks,
**-** Gbergz

**Comment by squeek502** [comment]
Thanks for the heads up!

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/squeek502/WailaHarvestability/commit/6300ed58a9df25c1d1b457aae00108fae08213cd :)
