### ISSUE TITLE
Possible to add JEI integration?

### ISSUE THREAD

**Issue by alemonplays** [squeek502/WailaHarvestability#73]
Hi,

would it be possible to add the harvest level tooltip to tools in JEI? Say, what Mining Level is X tool.

In large Modpacks it is hard to remember (and tidious to try them all out) what Pickaxe variant can mine X ore.

Thx in advance  and br
Mauricio

**Comment by squeek502** [comment]
I believe this is already an option in the config. See the `harvest.level.tooltip` config option (in the mod config, not the Waila config).

**Comment by squeek502** [comment]
Closing. Please re-open if that config option doesn't do what you expect.
