### ISSUE TITLE
Player unable to connect to server

### ISSUE THREAD

**Issue by Tyrius1** [squeek502/WailaHarvestability#74]
I have a player that was attempting to harvest an edelwood tree from forbidden arcanus in my pack The Cosmic Tree that crashed and is now unable to connect to my server.
They are getting this every time: 

https://pastebin.com/1jyRFmXi

Minecraft 1.15.2
forge-31.2.45
WailaHarvestability-mc1.15.2-1.1.12
Hwyla-forge-1.10.8-B72_1.15.2
WAWLA-1.15.2-3.0.4

**Comment by squeek502** [comment]
Looks like a Hwyla bug, not related to Waila Harvestability.
