### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by EltonRst** [squeek502/WailaHarvestability#78]
**After clone the project, at build time:**
![image](https://user-images.githubusercontent.com/15981323/107588950-a7174380-6be3-11eb-8f24-2bd597acf749.png)

**I using the following gradle version:**
![image](https://user-images.githubusercontent.com/15981323/107589080-f3fb1a00-6be3-11eb-8b25-3a992e1cb099.png)

**But, when i change gradle version to:**
![image](https://user-images.githubusercontent.com/15981323/107589207-41778700-6be4-11eb-9fdf-822227504556.png)

**I obtains the following:**
![image](https://user-images.githubusercontent.com/15981323/107589250-5c49fb80-6be4-11eb-9e7d-561f1ccbaa22.png)

**Then I do it:**
![image](https://user-images.githubusercontent.com/15981323/107589331-8ac7d680-6be4-11eb-9dc4-70682267a637.png)

 **But now, after run the build command, i obtains the following error:**
![image](https://user-images.githubusercontent.com/15981323/107589437-c662a080-6be4-11eb-8cc3-d497b2f43fd0.png)

**Can someone help me? I need to make some changes to the code and compile for minecraft version 1.16.2.**

**Comment by squeek502** [comment]
There is a 1.16 branch here: https://github.com/squeek502/WailaHarvestability/tree/1.16.x
