### ISSUE TITLE
Crash when looking at a mob spawner

### ISSUE THREAD

**Issue by digitalseraphim** [squeek502/WailaHarvestability#8]
MC version: 1.7.10
Forge Version: 10.13.0.1180
Waila version: 1.5.2a
WH version: 1.0.4

Specifically a spawner placed by Roguelike Dungeons. Error occurs at 22:41:23 (and at least 2 times before this, was verifying error). Verified also happens with same error with a spawner pulled from NEI.

Client did not crash, but lost connection to internal server (was playing SSP creative mode in normal world).

Error log: https://www.dropbox.com/s/5peidrnru9le9re/fml-client-latest.log

Edit: Apologies, I forgot to test without WH, and it appears it is probably a Waila error instead, feel free to close this issue.

**Comment by squeek502** [comment]
Yep, from [what I've seen elsewhere](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293062-refined-relocation-1-0-5-solves-your?comment=263), this is a bug with Waila in 1.7.10 that crashes when the server needs to send tooltip data to the client.
